spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:h2/schema.sql
    data: classpath:h2/data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
logging:
  level:
    jpastudy.restapi: debug
    org.hibernate: info
    org.hibernate.type: trace
